print("I visit this places")
countries = ["ukrane", "belorussia", "ausria", "italy", "germany"]
print(countries)
sorted(countries)
print(countries)
print(sorted(countries))
print(countries)
countries.reverse()
print(countries)
countries.sort()
print(countries)
print("I visit " + str(len(countries)) + " countries")
